<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjixpgr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjixpgr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHjixpgr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHjixpgr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHjixpgr\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hjixpgr',
    'container.build_id' => '5c028004',
    'container.build_time' => 1670964378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjixpgr');
